[[questions]]
type = "ShortAnswer"
prompt.prompt = """
If we list all the natural numbers below that are multiples of 3 or 5, we get 3, 5, 6, and 9. The sum of these multiples is 23.

Find the sum of all the multiples of or 3 or 5 below 1000.

You may reattempt this question as many times as you'd like.
"""
answer.answer = "233168"
id = "8d639838-79f3-427a-a7e8-3f6741897acf"
